security:
  token:
    secret: Our-Traengecino-trash-sucablyatski-BIT-Projectwork-goenk5-secret

#spring:
#  datasource:
#    url: jdbc:h2:file:./data/database
#    username: Traengcino
#    password: goenk

server:
  port:
