spring:
  datasource:
    url: ${jdbc:h2:file:./data/database}
    username: ${Traengcino}
    password: ${goenk}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

security:
  token:
    secret: ${Our-Traengecino-trash-sucablyatski-BIT-Projectwork-goenk5-secret}